version: '3'

services:
  postgis:
    image: cartoview/cartoview-postgis:latest
    restart: unless-stopped
    env_file:
      - ./postgis.env
    expose:
      - "5432"
    volumes:
      - "pg-data:/var/lib/postgresql"
    networks:
      -cartoview-internal:
  geoserver:
    image: cartoview/geoserver_docker:tomcat
    depends_on:
      - postgis
    restart: always
    expose:
      - "8080"
    volumes:
      - "./geoserver/data:/geoserver_data"
    env_file:
      - ./tomcat.env
    networks:
      -cartoview-external:
        ipv4_address: 10.5.0.2
      -cartoview-internal:
  cartoview:
    image: cartoview/cartoview:latest
    command: bash -c "python server.py"
    restart: unless-stopped
    hostname: cartoview
    depends_on:
      - postgis
      - geoserver
    env_file:
      - ./django.env
    volumes:
      - "./:/code/"
    networks:
      -cartoview-external:
        ipv4_address: 10.5.0.3
      -cartoview-internal:
    expose:
      - "8000"
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      -cartoview-external:
        ipv4_address: 10.5.0.4
      -cartoview-internal:
networks:
    -cartoview-external:
      driver: bridge
      ipam:
        config:
          - subnet: 10.5.0.0/16
    -cartoview-internal:
       internal: true
volumes:
  pg-data: